In [5]:
import torch
from torch import nn

In [9]:
n_pos = 64 #num_embeddings = size of the dictionary of embeddings
dim = 1024 #embedding_dim = size of each embedding vector

an embedding is just a lookup table.

when initializing, you create n_pos different indices, e.g., 1 for each word.
then, each word will be represented by dim floats which are calculated based on the weights of the embedding.
the weights are learned during training.

In [14]:
e = nn.Embedding(n_pos, dim)

In [15]:
e.weight.shape,e.weight

(torch.Size([64, 1024]),
 Parameter containing:
 tensor([[ 0.1920, -0.6611, -0.3977,  ..., -0.2789,  0.4131, -1.8262],
         [ 0.4764,  0.1507,  1.2597,  ...,  2.0319,  0.0784, -0.5667],
         [-0.8787,  1.3705,  0.3430,  ...,  1.0124, -0.8911,  1.4979],
         ...,
         [-0.2363, -1.3935, -0.3395,  ...,  0.0656, -0.8006,  0.6956],
         [-0.3866, -1.0277, -0.1494,  ...,  0.3896,  0.6084,  1.9942],
         [ 0.1433,  0.6445, -0.1725,  ...,  0.9806,  0.3934, -0.1202]],
        requires_grad=True))

to retrieve an embedding, you pass a list of indices (ints). for each of them, you will retrieve an embedding of size dim 

In [19]:
a = torch.randint(low=14,high=43,size=(1,522))
e(a).shape,e(a)

(torch.Size([1, 522, 1024]),
 tensor([[[ 0.3406,  0.9814,  1.0833,  ..., -1.2019,  1.0401,  0.5690],
          [ 0.8973,  0.8471,  0.7570,  ...,  0.1485, -1.1242, -1.2132],
          [-1.4073,  1.2259,  1.0179,  ..., -0.1685,  1.1933,  0.1820],
          ...,
          [-0.4392,  0.1687,  0.7692,  ..., -0.6926,  1.0820,  0.3284],
          [ 0.0185, -0.0246,  0.5937,  ...,  0.1380, -1.4950,  0.8448],
          [ 0.8973,  0.8471,  0.7570,  ...,  0.1485, -1.1242, -1.2132]]],
        grad_fn=<EmbeddingBackward0>))

In [20]:
a = torch.randint(low=14,high=43,size=(1,2378))
e(a).shape,e(a)

(torch.Size([1, 2378, 1024]),
 tensor([[[-0.4807, -1.0984, -1.1376,  ..., -0.1271,  1.0515, -1.1907],
          [-0.7495,  1.5448,  1.7666,  ..., -0.3674,  2.5782,  0.4107],
          [-0.4392,  0.1687,  0.7692,  ..., -0.6926,  1.0820,  0.3284],
          ...,
          [-0.8756, -0.8425,  0.6149,  ..., -0.6144,  0.7528, -0.3294],
          [-2.5290, -0.3384,  0.3816,  ..., -0.6995, -1.0060,  0.3404],
          [-1.1847,  0.2865,  0.0560,  ..., -1.4141, -1.4858,  0.6790]]],
        grad_fn=<EmbeddingBackward0>))

it seems that the problem is that the image that I am trying to predict has position values that are higher than n_pos which is used to construct the embedding, i.e., my max integer in the input is 74 > 64

In [21]:
a = torch.randint(low=60,high=70,size=(1,2378))
e(a).shape,e(a)

IndexError: index out of range in self

as you can see, it works if n_pos > max(input).
the reason is that there are basically only 64 entries in the lookup table while you are querying for entries that do not exist.

an analogy would be that you create a dictionary containing 64 words, but you would like to get an embedding of a word that is not in the dictionary

In [22]:
e2 = nn.Embedding(80, 1024)

In [23]:
e2(a).shape,e2(a)

(torch.Size([1, 2378, 1024]),
 tensor([[[ 1.0577, -0.9709,  0.9988,  ..., -0.4633,  0.0941,  1.2053],
          [-0.4897,  1.1873, -0.1907,  ..., -0.9569, -2.1632, -1.5653],
          [-0.7045,  2.2276, -2.4967,  ...,  1.4843, -0.4477, -1.1457],
          ...,
          [ 0.9064, -0.1055, -1.0278,  ...,  2.2449, -0.1209,  0.2769],
          [-0.7045,  2.2276, -2.4967,  ...,  1.4843, -0.4477, -1.1457],
          [-0.7045,  2.2276, -2.4967,  ...,  1.4843, -0.4477, -1.1457]]],
        grad_fn=<EmbeddingBackward0>))